/*
 * SelezioneCanali.java
 *
 * Created on 13 agosto 2008, 14.54
 */

package it.unibg.cs.jtvguide.graphic;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.io.File;
import java.util.Vector;

import javax.swing.JScrollPane;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author  Seba
 */
public class SelezioneCanali extends javax.swing.JFrame {

    /**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Vector<String> channelNameVector = new Vector <String>();
    private Vector<Boolean> channelSelectedVector = new Vector <Boolean>();
    private javax.swing.JPanel checkBoxList = new javax.swing.JPanel(new GridLayout(channelNameVector.size(),2));

    /** Creates new form SelezioneCanali */
    public SelezioneCanali() {
        initComponents();
        initConfig();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selezione Canali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void initConfig(){

    it.unibg.cs.jtvguide.xmltv.UserPreferences.setXmltvConfigFile(new File("tv_grab_it.conf"));
    it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.chargeVectors();
    channelNameVector = it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.getChannelNameVector();
    channelSelectedVector = it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.getChannelSelectedVector();

    Vector<javax.swing.JLabel> jLabelVector = new Vector <javax.swing.JLabel>();
    Vector<javax.swing.JCheckBox> jCheckBoxVector = new Vector <javax.swing.JCheckBox>();

    checkBoxList.setBackground(Color.WHITE);
    javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane(checkBoxList,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    javax.swing.JButton jButton1 = new javax.swing.JButton();
    jButton1.setText("Modifica File Di Configurazione");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

    this.setSize(380, 480);
    this.setResizable(false);
    this.setLayout(null);
    jButton1.setBounds(0, 400, 380, 50);
    jScrollPane1.setBounds(0, 0, 374, 400);



    for(int i=0;i<channelNameVector.size();i++)
    {
        javax.swing.JCheckBox jCheckBox = new javax.swing.JCheckBox();
        jCheckBox.setBackground(Color.WHITE);
        javax.swing.JLabel jLabel = new javax.swing.JLabel();

        jCheckBox.setSelected(channelSelectedVector.get(i));
        jLabel.setText(channelNameVector.get(i));

        jCheckBoxVector.add(jCheckBox);
        jLabelVector.add(jLabel);

        checkBoxList.add(jCheckBoxVector.get(i));
        checkBoxList.add(jLabelVector.get(i));
    }



    getContentPane().add(jScrollPane1);
    getContentPane().add(jButton1);

}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    Vector<String> channelNameVectorLocal=new Vector<String>();
    Vector<Boolean> channelSelectedVectorLocal=new Vector<Boolean>();

    Container c = ((Container) checkBoxList);

    for(int i=0;i<c.getComponents().length;i++)
    {
        if(c.getComponent(i).toString().contains("JCheckBox")){
            channelSelectedVectorLocal.add(((javax.swing.JCheckBox)c.getComponent(i)).isSelected());
        }
        if(c.getComponent(i).toString().contains("JLabel")){
            channelNameVectorLocal.add(((javax.swing.JLabel)c.getComponent(i)).getText());
        }
    }

    it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.chargeFile(channelNameVectorLocal, channelSelectedVectorLocal);
    this.dispose();
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelezioneCanali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
