/*
 * SelezioneCanali.java
 *
 * Created on 13 agosto 2008, 14.54
 */

package it.unibg.cs.jtvguide.graphic;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.util.Vector;

import javax.swing.JScrollPane;

/**
 *
 * @author  Seba
 */
public class SelezioneCanali extends javax.swing.JFrame {  
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Vector<String> channelNameVector = it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.getChannelNameVector();
    private Vector<Boolean> channelSelectedVector = it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.getChannelSelectedVector();
    private javax.swing.JPanel checkBoxList = new javax.swing.JPanel(new GridLayout(channelNameVector.size(),2));

    /** Creates new form SelezioneCanali */
    public SelezioneCanali() {
        initComponents();
        initConfig();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selezione Canali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void initConfig(){
    
    it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.chargeVectors();
        
    Vector<javax.swing.JLabel> jLabelVector = new Vector <javax.swing.JLabel>();
    Vector<javax.swing.JCheckBox> jCheckBoxVector = new Vector <javax.swing.JCheckBox>();
    
    this.setSize(380, 500);
    this.setResizable(false);
    this.setLayout(new GridLayout(2,1));
    
    checkBoxList.setBackground(Color.WHITE);
    
    for(int i=0;i<channelNameVector.size();i++)
    {
        javax.swing.JCheckBox jCheckBox = new javax.swing.JCheckBox();
        jCheckBox.setBackground(Color.WHITE);
        javax.swing.JLabel jLabel = new javax.swing.JLabel();
        
        jCheckBox.setSelected(channelSelectedVector.get(i));
        jLabel.setText(channelNameVector.get(i));        
        
        jCheckBoxVector.add(jCheckBox);
        jLabelVector.add(jLabel);
                
        checkBoxList.add(jCheckBoxVector.get(i));
        checkBoxList.add(jLabelVector.get(i));             
    }
    
    javax.swing.JButton jButton1 = new javax.swing.JButton();
    jButton1.setText("Modifica File Di Configurazione");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
    javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane(checkBoxList,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    
    getContentPane().add(jScrollPane1);
    getContentPane().add(jButton1);
           
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    Vector<String> channelNameVectorLocal=new Vector<String>();
    Vector<Boolean> channelSelectedVectorLocal=new Vector<Boolean>();
    
    Container c = ((Container) checkBoxList);
        
    for(int i=0;i<c.getComponents().length;i++)
    {
        if(c.getComponent(i).toString().contains("JCheckBox")){
            channelSelectedVectorLocal.add(((javax.swing.JCheckBox)c.getComponent(i)).isSelected());
        }
        if(c.getComponent(i).toString().contains("JLabel")){
            channelNameVectorLocal.add(((javax.swing.JLabel)c.getComponent(i)).getText());
        }
    }
       
    it.unibg.cs.jtvguide.xmltv.XMLTVConfigurator.chargeFile(channelNameVectorLocal, channelSelectedVectorLocal);
    this.dispose();
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelezioneCanali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
