/*
 * UserPreferences.java
 *
 * Created on 12 agosto 2008, 16.22
 */

package it.unibg.cs.jtvguide.graphic;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;


/**
 *
 * @author  Seba
 */
public class UserPreferences extends javax.swing.JFrame {
    
    private File configuration = new File("xmltv_configuration.txt");
    
    /** Creates new form UserPreferences */
    public UserPreferences() {
        initComponents();
        initConfig();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Preferences");
        setResizable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "5", "7", "10", "14" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Giorni di interesse:");

        jLabel2.setText("File di configurazione:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Aggiorna file di configurazione");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initConfig() {
        File dir = new File(".");
        if(dir.exists()){
            File[] list = dir.listFiles();
            for (int i = 0; i < list.length; i++){
                String fileName = list[i].toString();
                int jPtr = fileName.indexOf(".conf",0);
                if (jPtr>-1) {
                    String longName = (String) fileName.subSequence(2, fileName.length());
                    jComboBox2.addItem(longName);
                }
            }
        }
        try {
			BufferedReader reader = new BufferedReader(new FileReader(configuration));
			String lineRead = null;
			lineRead = reader.readLine();
                        jComboBox2.setSelectedItem(lineRead);
                        lineRead = reader.readLine();
                        jComboBox1.setSelectedItem(lineRead.toString());
        }
        catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    write_xmltv_configuration();
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void write_xmltv_configuration(){
    it.unibg.cs.jtvguide.xmltv.UserPreferences.setDays(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
    it.unibg.cs.jtvguide.xmltv.UserPreferences.setXmltvConfigFile(new File(jComboBox2.getSelectedItem().toString()));
    
    try {
        /*PrintStream ps = new PrintStream(new FileOutputStream(configuration));
        System.setOut(ps);
        System.out.println(jComboBox2.getSelectedItem().toString());
        System.setOut(ps);
        System.out.println(jComboBox1.getSelectedItem().toString());*/
        FileWriter fstream = new FileWriter(configuration);
        BufferedWriter out = new BufferedWriter(fstream);
        out.write(jComboBox2.getSelectedItem().toString()+'\n');
        out.write(jComboBox1.getSelectedItem().toString()+'\n');
        out.close();
        
    } 
    catch (Exception e) {
        // TODO Auto-generated catch block
	e.printStackTrace();
    }
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPreferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
